import type { Metadata } from "next";
import { Bebas_Neue } from "next/font/google";
import "./globals.css";
import Navbar from "./_components/Navbar";
import Footer from "./_components/Footer";
import { createClient } from "@/utils/supabase/server";

const bebas = Bebas_Neue({
  weight: "400",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "MyBarber",
  description: "Generated by create Barber app",
  icons: {
    icon: '/assets/icon.ico'
  },
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  const supabase = await createClient();
  const { data: { user }, error: userError } = await supabase.auth.getUser();
  
  let ruolo = null;

  if (user && !userError) {
    const { data: profile } = await supabase
      .from('profiles')
      .select('ruolo')
      .eq('id', user.id)
      .single();

    ruolo = profile?.ruolo ?? null;
  }

  return (
    <html lang="it">
      <body
        className={`${bebas.className} antialiased`}
      >
          <Navbar isLoggedIn={!!user} ruolo={ruolo}/>
          {children}
          <Footer />
      </body>
    </html>
  );
}
